import { Candidate } from './types';

const now = new Date().toLocaleString('pt-BR');

// Em uma aplicação real, estes dados viriam de uma API,
// possivelmente integrados com a plataforma vagas.com.
export const initialCandidates: Candidate[] = [
    {
        id: 'cand001',
        name: 'Ana Silva Costa',
        email: 'ana.silva@email.com',
        jobPosition: 'Enfermeira Pleno',
        jobId: 'v2771959',
        medicalExamDate: null,
        documents: [
            { id: 'doc_id_frente', name: 'Cédula de identidade - Frente', status: 'PENDING', lastUpdated: now },
            { id: 'doc_id_verso', name: 'Cédula de identidade - Verso', status: 'PENDING', lastUpdated: now },
            { id: 'doc_cpf_frente', name: 'CPF - Frente', status: 'PENDING', lastUpdated: now },
            { id: 'doc_cpf_verso', name: 'CPF - Verso', status: 'PENDING', lastUpdated: now },
            { id: 'doc_titulo_frente', name: 'Título de Eleitor - Frente', status: 'PENDING', lastUpdated: now },
            { id: 'doc_titulo_verso', name: 'Título de Eleitor - Verso', status: 'PENDING', lastUpdated: now },
            { id: 'doc_formacao_frente', name: 'Formação (conforme requisito do Cargo) - Frente', status: 'PENDING', lastUpdated: now },
            { id: 'doc_formacao_verso', name: 'Formação (conforme requisito do Cargo) - Verso', status: 'PENDING', lastUpdated: now },
            { id: 'doc_residencia', name: 'Comprovante de Residência', status: 'PENDING', lastUpdated: now },
            { id: 'doc_vacinacao', name: 'Carteira de Vacinação (exceto colaboradores ICESP)', status: 'PENDING', lastUpdated: now },
            { id: 'doc_ctps_foto', name: 'CTPS - Página da Foto', status: 'PENDING', lastUpdated: now },
            { id: 'doc_ctps_civil', name: 'CTPS - Página da Qualificação Civil', status: 'PENDING', lastUpdated: now },
            { id: 'doc_ctps_vinculo', name: 'CTPS – último vínculo o atual ativo que for conciliar', status: 'PENDING', lastUpdated: now },
            { id: 'doc_pis', name: 'Cartão do PIS / PASEP ou Extrato de PIS ATIVO', status: 'PENDING', lastUpdated: now },
            { id: 'doc_certidao', name: 'Certidão de Nascimento (SOLTEIROS) ou Casamento (CASADOS)', status: 'PENDING', lastUpdated: now },
            { id: 'doc_militar', name: 'Certificado Militar', status: 'PENDING', lastUpdated: now, optional: true },
            { id: 'doc_conselho', name: 'Carteira do Conselho Regional (atual)', status: 'PENDING', lastUpdated: now, optional: true },
            { id: 'doc_outro_vinculo', name: 'Declaração de outro vínculo Trabalhista', status: 'PENDING', lastUpdated: now, optional: true },
        ],
    },
    {
        id: 'cand002',
        name: 'Bruno Oliveira Martins',
        email: 'bruno.martins@email.com',
        jobPosition: 'Técnico de Enfermagem',
        jobId: 'v2771945',
        medicalExamDate: '15/08/2024 10:00',
        documents: [
            { id: 'doc_id_frente', name: 'Cédula de identidade - Frente', status: 'APPROVED', fileName: 'rg_frente.jpg', fileUrl: '#', lastUpdated: now, extractedData: { 'fullName': 'Bruno Oliveira Martins', 'documentNumber': '12.345.678-9' } },
            { id: 'doc_id_verso', name: 'Cédula de identidade - Verso', status: 'APPROVED', fileName: 'rg_verso.jpg', fileUrl: '#', lastUpdated: now },
            { id: 'doc_cpf_frente', name: 'CPF - Frente', status: 'APPROVED', fileName: 'cpf_frente.jpg', fileUrl: '#', lastUpdated: now, extractedData: { 'cpf': '222.222.222-22' } },
            { id: 'doc_cpf_verso', name: 'CPF - Verso', status: 'APPROVED', fileName: 'cpf_verso.jpg', fileUrl: '#', lastUpdated: now },
            { id: 'doc_titulo_frente', name: 'Título de Eleitor - Frente', status: 'REJECTED', fileName: 'titulo.pdf', fileUrl: '#', rejectionReason: 'Imagem ilegível.', lastUpdated: now },
            { id: 'doc_titulo_verso', name: 'Título de Eleitor - Verso', status: 'PENDING', lastUpdated: now },
            { id: 'doc_formacao_frente', name: 'Formação (conforme requisito do Cargo) - Frente', status: 'APPROVED', fileName: 'diploma.pdf', fileUrl: '#', lastUpdated: now },
            { id: 'doc_formacao_verso', name: 'Formação (conforme requisito do Cargo) - Verso', status: 'PENDING', lastUpdated: now },
            { id: 'doc_residencia', name: 'Comprovante de Residência', status: 'APPROVED', fileName: 'conta_luz.pdf', fileUrl: '#', lastUpdated: now },
            { id: 'doc_vacinacao', name: 'Carteira de Vacinação (exceto colaboradores ICESP)', status: 'APPROVED', fileName: 'vacina.pdf', fileUrl: '#', lastUpdated: now },
            { id: 'doc_ctps_foto', name: 'CTPS - Página da Foto', status: 'ANALYSING', fileName: 'ctps_foto.jpg', fileUrl: '#', lastUpdated: now },
            { id: 'doc_ctps_civil', name: 'CTPS - Página da Qualificação Civil', status: 'PENDING', lastUpdated: now },
            { id: 'doc_ctps_vinculo', name: 'CTPS – último vínculo o atual ativo que for conciliar', status: 'PENDING', lastUpdated: now },
            { id: 'doc_pis', name: 'Cartão do PIS / PASEP ou Extrato de PIS ATIVO', status: 'PENDING', lastUpdated: now },
            { id: 'doc_certidao', name: 'Certidão de Nascimento (SOLTEIROS) ou Casamento (CASADOS)', status: 'PENDING', lastUpdated: now },
            { id: 'doc_militar', name: 'Certificado Militar', status: 'NOT_APPLICABLE', lastUpdated: now, optional: true },
            { id: 'doc_conselho', name: 'Carteira do Conselho Regional (atual)', status: 'PENDING', lastUpdated: now, optional: true },
            { id: 'doc_outro_vinculo', name: 'Declaração de outro vínculo Trabalhista', status: 'NOT_APPLICABLE', lastUpdated: now, optional: true },
        ],
    },
     {
        id: 'cand003',
        name: 'Carla Dias Ferreira',
        email: 'carla.ferreira@email.com',
        jobPosition: 'Analista Administrativo',
        jobId: 'v2771808',
        medicalExamDate: null,
        documents: [
            { id: 'doc_id_frente', name: 'Cédula de identidade - Frente', status: 'APPROVED', lastUpdated: now, fileName:'rg_frente.png', fileUrl:'#', extractedData: {'fullName': 'Carla Dias Ferreira', 'documentNumber': '98.765.432-1'} },
            { id: 'doc_id_verso', name: 'Cédula de identidade - Verso', status: 'APPROVED', lastUpdated: now, fileName:'rg_verso.png', fileUrl:'#' },
            { id: 'doc_cpf_frente', name: 'CPF - Frente', status: 'APPROVED', lastUpdated: now, fileName:'cpf_frente.png', fileUrl:'#', extractedData: {'cpf': '333.333.333-33'} },
            { id: 'doc_cpf_verso', name: 'CPF - Verso', status: 'APPROVED', lastUpdated: now, fileName:'cpf_verso.png', fileUrl:'#' },
            { id: 'doc_titulo_frente', name: 'Título de Eleitor - Frente', status: 'APPROVED', lastUpdated: now, fileName:'titulo_frente.png', fileUrl:'#' },
            { id: 'doc_titulo_verso', name: 'Título de Eleitor - Verso', status: 'APPROVED', lastUpdated: now, fileName:'titulo_verso.png', fileUrl:'#' },
            { id: 'doc_formacao_frente', name: 'Formação (conforme requisito do Cargo) - Frente', status: 'APPROVED', lastUpdated: now, fileName:'form_frente.png', fileUrl:'#' },
            { id: 'doc_formacao_verso', name: 'Formação (conforme requisito do Cargo) - Verso', status: 'APPROVED', lastUpdated: now, fileName:'form_verso.png', fileUrl:'#' },
            { id: 'doc_residencia', name: 'Comprovante de Residência', status: 'APPROVED', lastUpdated: now, fileName:'residencia.png', fileUrl:'#' },
            { id: 'doc_vacinacao', name: 'Carteira de Vacinação (exceto colaboradores ICESP)', status: 'APPROVED', lastUpdated: now, fileName:'vacina.png', fileUrl:'#' },
            { id: 'doc_ctps_foto', name: 'CTPS - Página da Foto', status: 'APPROVED', lastUpdated: now, fileName:'ctps_foto.png', fileUrl:'#' },
            { id: 'doc_ctps_civil', name: 'CTPS - Página da Qualificação Civil', status: 'APPROVED', lastUpdated: now, fileName:'ctps_civil.png', fileUrl:'#' },
            { id: 'doc_ctps_vinculo', name: 'CTPS – último vínculo ou atual ativo que for conciliar', status: 'APPROVED', lastUpdated: now, fileName:'ctps_vinculo.png', fileUrl:'#' },
            { id: 'doc_pis', name: 'Cartão do PIS / PASEP ou Extrato de PIS ATIVO', status: 'APPROVED', lastUpdated: now, fileName:'pis.png', fileUrl:'#' },
            { id: 'doc_certidao', name: 'Certidão de Nascimento (SOLTEIROS) ou Casamento (CASADOS)', status: 'APPROVED', lastUpdated: now, fileName:'certidao.png', fileUrl:'#' },
            { id: 'doc_militar', name: 'Certificado Militar', status: 'NOT_APPLICABLE', lastUpdated: now, optional: true },
            { id: 'doc_conselho', name: 'Carteira do Conselho Regional (atual)', status: 'NOT_APPLICABLE', lastUpdated: now, optional: true },
            { id: 'doc_outro_vinculo', name: 'Declaração de outro vínculo Trabalhista', status: 'NOT_APPLICABLE', lastUpdated: now, optional: true },
        ]
    },
    {
        id: 'cand004',
        name: 'Daniel Gomes Lima',
        email: 'daniel.lima@email.com',
        jobPosition: 'Enfermeira Pleno',
        jobId: 'v2771762',
        medicalExamDate: '20/08/2024 14:00',
        documents: new Array(18).fill(null).map((_, i) => ({
            id: `doc_${i}`,
            name: `Documento ${i + 1}`,
            status: 'APPROVED',
            lastUpdated: now,
            fileName: `doc_${i}.pdf`,
            fileUrl: '#'
        }))
    }
];